### ISSUE TITLE
[Frontend] Create production and development environments for Frontend

### ISSUE THREAD

**Issue by danalexandrunicoara** [danalexandrunicoara/northwind-app#2]
Replace _proxy_ with environment variables.

Inside _prackage.json_ there is the following line: `"proxy": "http://localhost:4000",`. This will be replaced.

**Comment by alexPopNicolae** [comment]
Done! Just needs to be reviewed and merged!

**Comment by danalexandrunicoara** [comment]
Review is accepted. Please close the issue after merging the code.

**Comment by alexPopNicolae** [comment]
done
