### ISSUE TITLE
[BUG/FE] fix missing i18next packages from paclage.json

### ISSUE THREAD

**Issue by alexPopNicolae** [danalexandrunicoara/northwind-app#20]
i18next packages are missing because of the fact that --save flag was not run at install

**Comment by danalexandrunicoara** [comment]
The following issues was fixed with [this](https://github.com/TheCoffeeMaker/CollectionMaster/commit/5b76d426c0ff7828fbdf9c2d1c16b291d23f1f1a) commit.
