### ISSUE TITLE
[Frontend] Create a wrapper over Axios library

### ISSUE THREAD

**Issue by danalexandrunicoara** [danalexandrunicoara/northwind-app#3]
REST API Helper which will offer HTTP verbs like GET, POST, DELETE and UPDATE.

Create business API logic.

**Comment by alexPopNicolae** [comment]
Done! Needs review and merge!

**Comment by danalexandrunicoara** [comment]
Review is accepted. Please close the issue after merging the code.

**Comment by alexPopNicolae** [comment]
done
